import type { InspectionStatus, TankStatus } from '@/models/aquaculture';

export const StatusCopy: Record<TankStatus, string> = {
  normal: '양호',
  caution: '의심',
  suspicious: '경고',
};

export const BinaryStatusCopy = {
  normal: '양호',
  suspicious: '의심',
} as const;

export const InspectionStatusCopy: Record<InspectionStatus, string> = {
  pending: '판정 대기',
  completed: '판정 완료',
  failed: '판정 실패',
};

export const AppCopy = {
  common: {
    back: '뒤로',
    home: '홈으로',
    close: '닫기',
    cancel: '취소',
    save: '저장',
    retry: '재시도',
    tankGroupFallback: '수조군',
    sharedGroupFallback: '공유 계통',
    unknownGroup: '미지정 계통',
    emptyStockedInfo: '광어 입식 정보 미입력',
    genericError: '요청을 완료하지 못했습니다. 잠시 후 다시 시도하세요.',
    loadError: '서버에서 최신 양식장 정보를 불러오지 못했습니다.',
    offlineMode: '샘플 데이터 모드',
  },
  navigation: {
    result: '분석 결과',
    tankInfo: '수조 정보',
    guidance: 'AI 대응 제안',
    addTank: '수조 추가',
    editTank: '수조 편집',
    home: '홈',
    tankStatus: '수조 목록',
    capture: '촬영',
  },
  farm: {
    defaultName: '제주 성산 광어양식장',
  },
  validation: {
    tankIdRequired: '수조 ID를 입력하세요.',
    duplicateTankId: '이미 등록된 수조 ID입니다.',
    tankNotFound: '수정할 수조를 찾을 수 없습니다.',
  },
  errors: {
    inspectionUnavailable: '서버 판정 요청이 완료되지 않았습니다. 네트워크 상태를 확인한 뒤 재시도하세요.',
    requestTimeout: '요청 시간이 초과되었습니다.',
    network: '네트워크 요청에 실패했습니다.',
    invalidResponse: '서버 응답 형식이 올바르지 않습니다.',
  },
  prototype: {
    normalSummary: '명확한 병변 후보가 감지되지 않았습니다. 정기 추적 촬영을 유지하세요.',
    cautionSummary: '작은 병변 후보가 있으나 경계가 약합니다. 동일 수조를 24시간 내 재촬영하세요.',
    suspiciousSummary: '붉은 반점과 기부 변색 후보가 함께 감지되었습니다. 같은 수조군 격리 관찰과 전문가 확인이 필요합니다.',
    weakLesion: '약한 병변',
    erythemaCandidate: '홍반 후보',
    discolorationCandidate: '변색 후보',
  },
  notFound: {
    title: '화면을 찾을 수 없습니다',
    body: '요청한 경로가 앱의 수조 점검 흐름에 없습니다.',
  },
  addTank: {
    tankId: '수조 ID',
    tankIdPlaceholder: '예: D-02',
    groupId: '수조군 (취수·배수 계통)',
    groupIdPlaceholder: '예: 1계통',
    stockedInfo: '입식 정보',
    stockedInfoPlaceholder: '입식일 · 마릿수 · 크기 등',
    active: '수조 활성',
    activeHint: '수조 출하 완료 시 비활성화 해주세요.\n점검 내역 등의 이력은 보존됩니다.',
  },
  home: {
    todayStatus: '오늘의 수조 상태',
    loading: '수조 정보를\n불러오고 있어요',
    loadFailed: '수조 정보를\n불러오지 못했어요',
    allNormal: '모든 수조가\n양호한 상태예요',
    inspectNow: '수조 바로 확인하기',
    alertHeadline: (grade: string, count: number) => `${grade} 단계의 수조가\n${count}개 발견됐어요`,
  },
  tank: {
    notFound: '수조를 찾을 수 없습니다',
    inactive: ' · 비활성',
    linkedWarning: (tankId: string) => `${tankId} 계통 주의`,
    captureThis: '이 수조 촬영하기',
    edit: '편집',
    history: '점검 내역',
    diagnosis: '진단',
    normalSummary: '명확한 병변 후보가 감지되지 않았어요',
    normalDiagnosis: '이상 없음',
    emptyHistory: '아직 점검 기록이 없어요. 이 수조를 촬영하면 분석 결과가 카드로 쌓입니다.',
    pendingSummary: 'AI 분석 결과를 기다리는 중이에요.',
    noCapture: '촬영 기록 없음',
    lastCapture: (value: string) => `최근 촬영 ${value}`,
  },
  camera: {
    close: '닫기',
    title: '수조 사진 분석',
    selectTank: '촬영할 수조를 선택하세요',
    noTanks: '등록된 수조가 없습니다',
    noTanksBody: '수조를 추가한 뒤 사진 분석을 시작할 수 있습니다.',
    addTank: '수조 추가',
    selectedTank: '선택된 수조',
    gallery: '갤러리 선택',
    galleryShort: '갤러리',
    takePhoto: '촬영하기',
    latestAnalysis: (value: string) => `최근 분석 ${value}`,
    noAnalysis: '아직 분석 기록 없음',
    saving: '사진 저장 중',
    waitingPermission: '카메라 권한 대기 중',
    preparing: '카메라 준비 중',
    tapToCapture: '탭하여 촬영',
    permissionTitle: '카메라 권한이 필요합니다',
    permissionDeniedBody: '설정에서 카메라 접근을 허용하거나 갤러리 사진을 선택하세요.',
    permissionBody: '수조 점검용 사진을 촬영하려면 카메라 권한이 필요합니다.',
    requestPermission: '권한 요청',
    checkingPermission: '카메라 권한을 확인하고 있습니다.',
    backToSelection: '수조 선택으로 돌아가기',
    framingGuide: '넙치의 윗면과 수평이 되도록 맞춰 주세요',
    review: {
      selectTank: '분석할 수조를 선택해 주세요',
      tankId: '수조 ID',
      selectTankPlaceholder: '수조를 선택해 주세요',
      noTanks: '등록된 수조가 없습니다',
      checkPhoto: '촬영 또는 업로드한 사진을\n다시 한번 확인해 주세요',
      photoAccessibilityLabel: '촬영 또는 업로드한 광어 사진',
      previous: '이전',
      next: '다음',
      openTankList: '수조 목록 열기',
      closeTankList: '수조 목록 닫기',
    },
    errors: {
      cameraPermissionRequest: '카메라 권한 요청을 완료하지 못했습니다.',
      mediaPermission: '사진 보관함 접근 권한이 필요합니다.',
      selectedPhoto: '선택한 사진을 불러오지 못했습니다.',
      gallery: '갤러리에서 사진을 선택하지 못했습니다. 다시 시도하세요.',
      cameraPermission: '카메라 권한이 필요합니다.',
      cameraNotReady: '카메라가 아직 준비되지 않았습니다.',
      capturedPhoto: '촬영한 사진을 저장하지 못했습니다.',
      savePhoto: '사진을 저장하지 못했습니다. 다시 촬영하세요.',
      mountCamera: '카메라를 시작하지 못했습니다. 갤러리 사진을 사용할 수 있습니다.',
    },
  },
  result: {
    filters: { all: '전체', normal: '양호', suspicious: '의심' },
    notFound: '분석 결과를 찾을 수 없습니다',
    reportTitle: (tankId: string) => `${tankId} 분석 보고서`,
    responsePlan: '대응 방안',
    capturedAt: '점검 일시',
    tankGrade: '수조 단계',
    healthyObjects: '양호 개체',
    suspiciousObjects: '의심 개체',
    diseaseDiagnosis: '질병 진단',
    infectionRisk: '감지된 개체 중 1개 이상 감염 의심',
    objectDetails: '개체별 상세 분석',
    emptyFilter: '선택한 상태의 개체가 없습니다',
    pendingTitle: '분석 중이에요',
    pendingBody: '잠시만 기다려 주세요',
    failedTitle: '분석 실패',
    sampleFallback: '샘플 결과 보기',
    selectedObject: '선택 개체 분석',
    symptom: '증상',
    suspectedDisease: '의심 질병',
    observedPart: '관찰 부위',
    noDisease: '의심 질병 없음',
    notDetected: '감지 없음',
    disclaimer: '본 결과는 확률적 참고치이며 확진이 아니에요.\n격리·투약·신고 등 최종 판단은 전문가 확인이 필요해요.',
    suspicious: '의심',
    normal: '양호',
    diseaseCandidate: '질병 후보',
    none: '없음',
    overallAction: '종합 대처 방안',
    noFinding: '특이 소견 없음',
    objectEvidence: (index: number, lesion: string, summary: string) => `${index}번 개체에서 ${lesion} 후보가 감지되었습니다. ${summary}`,
    normalResponseTitle: '정기 추적 관찰을 유지하세요',
    normalResponseAction: '현재 수조는 즉시 분리 조치보다 정기 촬영과 수조군 기록 유지가 우선입니다.',
    regularCaptureTitle: '정기 촬영 유지',
    regularCaptureBody: '동일 수조를 다음 점검 주기에 맞춰 다시 촬영합니다.',
    preserveRecordsTitle: '수조군 기록 보존',
    preserveRecordsBody: (group: string) => `${group}의 수온, 섭이, 폐사 기록을 함께 남깁니다.`,
    suspiciousResponseTitle: '수조 단위 분리 관찰을 우선하세요',
    suspiciousResponseAction: (group: string) => `${group}은 작업 동선을 분리하고 의심 개체를 재촬영한 뒤, 원본 사진과 수조 이력을 묶어 전문가 확인을 요청하세요.`,
    separateRouteTitle: '수조군 작업 동선 분리',
    separateRouteBody: (group: string) => `${group}의 기구, 작업자 동선, 배수 접점을 인접 수조와 분리합니다.`,
    recaptureTitle: '의심 개체 재촬영',
    recaptureBody: (count: number) => `의심 개체 ${count}마리를 같은 조건으로 재촬영해 병변 반복 여부를 확인합니다.`,
    expertReviewTitle: '전문가 확인 요청',
    expertReviewBody: '원본 사진, AI 결과, 수조 이력을 묶어 수산질병관리원 등 전문가에게 확인을 요청합니다.',
  },
  guidance: {
    procedureTitle: '권장 대응 절차',
    insufficientTitle: '근거 불충분',
    insufficientBody: '의심·주의 등급과 병변 근거가 충분하지 않아 대응 제안을 생성하지 않습니다. 임의 생성 대신 수산질병관리원 등 전문가에게 문의하세요.',
    loadingTitle: '대응 제안 생성 중',
    loadingBody: '등급과 병변 근거를 기준으로 현장 대응·신고 안내를 구성하고 있어요.',
    heroTitle: (group: string) => `${group} 차단 후 공식 절차 확인`,
    fieldResponse: '현장 대응',
    recaptureTitle: '동일 수조 재촬영',
    recaptureBody: '개체를 물 밖으로 꺼내서 1회 이상 재촬영 후 병변 후보가 반복되는지 확인하세요.',
    blockGroupTitle: '같은 수조군 차단',
    blockGroupBody: (group: string) => `${group}의 취수, 배수, 기구, 작업 동선을 분리하여 수조를 격리하세요.`,
    expertTitle: '전문가 확인',
    expertBody: 'AI 결과, 원본 사진, 수조 정보를 묶어 수산질병관리원 등 전문가에게 확인을 요청합니다.',
    expertModalBody: (group: string) => `${group}의 취수, 배수, 기구, 작업 동선을 분리하여 수조를 묶어 수산질병관리원의 전문가에게 확인을 요청하세요.`,
    manualCitations: [
      '국립수산과학원 ‘양식 넙치 메뉴얼’ 20p',
      '국립수산과학원 ‘양식 넙치 메뉴얼’ 124p',
    ],
    modalDisclaimer: 'AI 판정은 확진이 아니에요. 방역·투약·출하 제한·신고는 양식장 관리자 책임 아래 공식 지침과 전문가 판단으로 진행하세요.',
    reporting: '신고 절차',
    reportingBody: '바이러스성출혈성패혈증(VHS) 등 법정 전염병 또는 대량 폐사 의심 상황은 공식 기관 안내와 현행 법령을 확인해 신고 여부를 결정해야 합니다. 이 화면은 신고 판단을 대체하지 않습니다.',
    sources: '인용 출처',
    disclaimer: 'AI 판정은 확진이 아닙니다. 방역·투약·출하 제한·신고는 양식장 관리자 책임 아래 공식 지침과 전문가 판단을 기준으로 진행하세요.',
    citations: [
      { title: '국립수산과학원 수산생물질병정보', url: 'https://www.nifs.go.kr/portal/fg/fisgA/actionDiseaseSearch.do' },
      { title: '국립수산과학원 질병예방 및 진단', url: 'https://nifs.go.kr/portal/pcon0000271/systA/actionConts.do' },
      { title: '국가법령정보센터: 수산생물질병 관리법 시행규칙', url: 'https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=193193' },
    ],
  },
} as const;
